# Generated by Django 5.0 on 2024-04-05 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0003_reserva_descripcion_reserva_fecha_reserva_hora_fin_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("disponible", models.BooleanField(default=True)),
                ("capacidad", models.IntegerField()),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="reserva",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="bookings.sala",
            ),
        ),
    ]
